[IDLE-66] test&docs: user-service rest docs 설정
SWM-IDLE/mybrary pull request #14
Opened 2023-07-07 06:37 UTC by 0112leesy

## 🧑‍💻 작업 사항
코드가 조금 많지만 주요 작업 사항은 프로필, 팔로우 API 문서 생성입니다.
API 요청/응답 값이 적절한지 위주로 확인해주시면 좋겠습니다!
유사한 dto가 많아서 dto 클래스명과 필드명 또한 적절한지 확인 부탁드립니다!

### REST docs + Swagger UI 설정
- spring rest docs, restdocs-api-spec, swagger generator 의존성 추가
- user-service.json 으로 api 문서가 작성되도록 함
- 생성된 json 문서를 s3 버킷에 수동 업로드 (추후 자동화 예정)
- s3 버킷 내의 json 문서들을 불러와 Swagger UI 를 띄우는 EC2 인스턴스 생성
  - http://ec2-43-201-135-172.ap-northeast-2.compute.amazonaws.com
<img width="991" alt="image" src="https://github.com/SWM-IDLE/mybrary/assets/78717113/96304064-7d1d-4e6c-9bc0-52ab6c1c2969">
<img width="988" alt="image" src="https://github.com/SWM-IDLE/mybrary/assets/78717113/b71ea34e-3b25-4220-b82f-9f83b7acf293">

### 프로필,팔로우 API 테스트 코드 작성 및 API 문서 생성
- Profile API
    - 프로필 조회: get users/profile
    - 프로필 수정: put users/profile
    - 프로필 이미지 조회: get users/profile/image
    - 프로필 이미지 등록: put users/profile/image
    - 프로필 이미지 삭제: delete users/profile/image

- Follow API
    - 팔로워 목록 조회: get users/followers
    - 팔로잉 목록 조회: get users/followings
    - 팔로우: post users/follow
    - 언팔로우: delete users/follow
    - 언팔로잉: delete users/follwer

실질적인 기능은 각각 다음 이슈에서 구현 예정
- Profile API: [IDLE-105], [IDLE-106]
- Follow API: [IDLE-107]

### 기타 수정 사항
- presentation layer의 dto와 service layer의 dto를 분리:  presentaiton layer에 요청된 값을 service dto로 변환하여 서비스 호출
- 회원 가입 기능을 authentication 도메인에서 user 도메인으로 이동: UserRepository 의존성을 최대한 끊어내기 위함
- Book Service와의 일관성을 위해 패키지 구조 변경 및 SuccessResponse 클래스 생성: 일관된 API 응답 형식 지정

<br><br>

## 🔗 링크

<br><br>

## 🐰 시급한 정도

🐢 천천히 : 급하지 않습니다.

<br><br>

## 📖 참고 사항
1. 현재 로그인 한 회원을 식별할 때 '로그인 아이디' 값을 사용하고 있는데, 로그인 아이디 값으로 UUID가 부여되는 소셜 로그인 회원과는 다르게 자체 회원가입 한 사용자들에겐 로그인 아이디가 개인 정보로 취급될 수 있어 **회원 식별을 위한 '회원 코드'를 따로 부여하는 것**을 고려해보아야 할 것 같습니다.

2. REST docs 설정 후 Github actions를 통한 임시 배포 파이프라인을 구축하려 했으나 프로필,팔로우 API 기능 구현을 우선적으로 진행하겠습니다. AWS를 활용한 배포 파이프라인 구축을 학습한 뒤 파이프라인 구축을 시도해보겠습니다.

2023-07-07 08:18 UTC, minnseong requested changes
수고 많으셨습니다!

2023-07-07 08:18 UTC, minnseong commented on user-service/src/main/java/kr/mybrary/userservice/user/presentation/UserController.java
> +    @PostMapping("/profile/image")
r1: 기존의 프로필 이미지를 수정하는 것이기 때문에, @PostMapping 보다는 @PutMapping이 더 적합한 것 같습니다.

2023-07-08 14:28 UTC, 0112leesy commented on user-service/src/main/java/kr/mybrary/userservice/authentication/UserDetailsServiceImpl.java
> +    @Override
readOnly 옵션이 있는지 몰랐네요🫢 UserDetailsServiceImpl에서는 User DB를 조회만 하기 때문에 readOnly=true로 설정하는 것이 좋아보입니다 수정하도록 하겠습니닷!

2023-07-08 14:29 UTC, 0112leesy commented on user-service/src/main/java/kr/mybrary/userservice/global/jwt/filter/JwtExceptionFilter.java
> +
try-catch로 수정하고 테스트해보겠습니다! 좋은 의견 감사합니당👍

2023-07-08 14:32 UTC, 0112leesy commented on user-service/src/main/java/kr/mybrary/userservice/user/domain/dto/request/FollowServiceRequest.java
> +    public static FollowServiceRequest of(String loginId, FollowRequest followRequest) {
아하 그러네요 UserController에서 Request Dto를 열어 String targetId 값만 ServiceRequest Dto로 전달해주는 방법을 고려해보겠습니다

2023-07-08 14:34 UTC, 0112leesy commented on user-service/src/main/java/kr/mybrary/userservice/user/presentation/UserController.java
> +    @PostMapping("/profile/image")
🫢 어머낫 중요한 부분을 캐치해주셨네요 서둘러 수정하겠슴다!

2023-07-08 16:59 UTC, 0112leesy commented on user-service/src/main/java/kr/mybrary/userservice/user/presentation/UserController.java
> +    @PostMapping("/profile/image")
Multipart 요청은 HTTP 메소드가 POST로 강제되어서 파일 전송 api의 경우 post로 처리해야 될 것 같습니다..! 현재 스프링이 버전업 되면서 http 메소드를 지정해줄 수는 있으나 HTML 폼(form) 요청이 GET과 POST 만을 지원하기 때문에 조금 더 논의해보아야 할 것 같습니다 😭
관련 레퍼런스 입니다
https://mangkyu.tistory.com/218

2023-07-08 17:04 UTC, 0112leesy commented on user-service/src/main/java/kr/mybrary/userservice/user/presentation/UserController.java
> +    @PostMapping("/profile/image")
또한 프로필 이미지 등록 api에서 단순히 이미지 파일만 받을지, 추가 정보를 받을지에 따라 다음과 같이 구현될 수 있을 것 같습니다.
1. MultipartFile과 Json을 모두 갖는 dto로 구성
2. 단순히 MultipartFile 객체로 처리

두 경우에 따라 요청 값을 @RequestPart로 받을지 @ModelAttribute 로 받을지 고려해보겠습니다.

2023-07-08 17:52 UTC, minnseong commented on user-service/src/main/java/kr/mybrary/userservice/user/presentation/UserController.java
> +    @PostMapping("/profile/image")
위 레퍼런스에서 말하는 내용은 HTML form 요청은 GET과 POST 밖에 지원하지 않는다라는 내용인 것 같습니다. Multipart 요청과는 별개인 내용인 것 같습니다. multipart가 HTML form을 통해서 요청이 온다면 GET과 POST를 사용해야 하는 것이 맞지만, 그게 아니라면 PUT 사용해도 되는 것 같습니다.

아래 레퍼런스를 보면 실제 플러터에서 이미지를 업로드하거나 변경할 때 HTTP Method Patch를 사용하는 것을 확인할 수 있습니다. 
https://dkswnkk.tistory.com/334

2023-07-09 11:24 UTC, 0112leesy commented on user-service/src/main/java/kr/mybrary/userservice/user/presentation/UserController.java
> +    @PostMapping("/profile/image")
확인해보니 Multipart 요청은 put, patch로도 보낼 수 있네요! mockmvc에서의 multipart 요청이 post로 강제 되어서 제가 착각한 것 같습니다😅
```
ResultActions actions = mockMvc.perform(
                RestDocumentationRequestBuilders.multipart(BASE_URL+"/profile/image")
                        .file(profileImage)
                        .with(request -> {
                            request.setMethod("PUT");
                            return request;
                        })
                        .with(csrf())
                        .header("USER-ID", LOGIN_ID));
```

위와 같이 multipart 요청에 대해서 request 메서드를 지정해주는 코드를 추가해주니 put으로 요청이 잘 테스트됩니다~!

2023-07-09 11:27 UTC, 0112leesy commented on user-service/src/main/java/kr/mybrary/userservice/user/presentation/UserController.java
> +    @PostMapping("/profile/image")
다만 현재 사용중인 [restdocs-api-spec](https://github.com/ePages-de/restdocs-api-spec) 에서 multipart parameter을 문서화하기 위한 resource snippet parameter을 지원하지 않아서 문서화는 어려울 것 같습니다
현재 지원되는 resource snippet parameter는 다음과 같습니다
![image](https://github.com/SWM-IDLE/mybrary/assets/78717113/33bda951-1dd9-40a3-8651-ab5ed2f9242c)

2023-07-09 12:22 UTC, 0112leesy commented on user-service/src/main/java/kr/mybrary/userservice/global/jwt/filter/JwtExceptionFilter.java
> +
수정한 결과 예외 처리 기능이 문제 없이 동작하지만 예외 처리 작업을 따로 분리하는 것이 JwtAuthenticationProcessingFilter를 보다 깔끔하게 유지할 수 있을 것 같습니다. 원래대로 유지하겠습니다!

2023-07-09 12:31 UTC, minnseong commented on user-service/src/main/java/kr/mybrary/userservice/user/presentation/UserController.java
> +    @PostMapping("/profile/image")
수고하셨습니다. restdocs-api-spec에서 문서화되지 않는 부분에 있어서는 description에다 적어놓으면 좋을 것 같습니다!!

2023-07-09 12:31 UTC, minnseong approved these changes

2023-07-09 12:42 UTC, 0112leesy commented on user-service/src/main/java/kr/mybrary/userservice/user/presentation/UserController.java
> +    @PostMapping("/profile/image")
<img width="970" alt="image" src="https://github.com/SWM-IDLE/mybrary/assets/78717113/3010351c-143b-44b6-b403-fcc654a39e6e">

description 업데이트 했습니다!

2023-07-09 12:44 UTC, merged